// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileService is an autogenerated mock type for the FileService type
type FileService struct {
	mock.Mock
}

// BuildPresignedURL provides a mock function with given fields: params
func (_m *FileService) BuildPresignedURL(params map[string]interface{}) (map[string]interface{}, error) {
	ret := _m.Called(params)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) map[string]interface{}); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
