version: '3'
services:
  app:
    container_name: fircee_api
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - api:/usr/src/app
    depends_on:
      - ficree-postgres
    networks:
      - ficree  
  ficree-postgres:
    image: postgres:latest
    container_name: ficree_db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var//lib/postgresql/data
    networks:
      - ficree

volumes:
  api:
  database_postgres:

networks:
  ficree:
    driver: bridge